CREATE TABLE ClientFamilyHistoryTBL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  MEDPAL BIGINT NULL,
  RelationshipTypeID INTEGER UNSIGNED NULL,
  MedicalConditionID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MedicalComditionTBL (
  ID INTEGER UNSIGNED NOT NULL,
  MedicalCondition VARCHAR(50) NULL,
  PRIMARY KEY(ID)
);


