CREATE TABLE ClientFamilyHistoryTBL (
  ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  MEDPAL BIGINT(20) UNSIGNED NULL,
  RelationshipTypeID INTEGER(10) UNSIGNED NULL,
  MedicalConditionID INTEGER(10) UNSIGNED NULL,
  FamilyResponce CHAR NULL,
  PRIMARY KEY(ID)
);


