CREATE TABLE ProviderTBL (
  ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  TypeID INTEGER(10) UNSIGNED NULL,
  FullNameID BIGINT(20) UNSIGNED NULL,
  SpecialtyID INTEGER(10) UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX indexType(TypeID)
);


