CREATE TABLE UpinTBL (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  UPIN CHAR(6) NOT NULL,
  LastName VARCHAR(20) NULL,
  FirstName VARCHAR(14) NULL,
  MI VARCHAR(6) NULL,
  Suffix VARCHAR(3) NULL,
  CredentialCodes CHAR(3) NULL,
  LiscenceState CHAR(2) NULL,
  ZIP VARCHAR(9) NULL,
  PrimarySpecialtyCode CHAR(2) NULL,
  PRIMARY KEY(ID),
  INDEX indexUPIN(UPIN)
);


